In [2]:
import numpy as np

In [3]:
matrix1 = np.array([(1,2,3),(4,5,6),(7,8,9)])

In [4]:
matrix1.shape

(3, 3)

In [5]:
print(matrix1.ndim)

2


In [6]:
print(matrix1.size)

9


In [7]:
print(matrix1.reshape(1,9))

[[1 2 3 4 5 6 7 8 9]]


In [8]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [10]:
print(np.full((3,3),5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [11]:
print(np.empty((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
print(np.empty(2))

[9.03365872e-308 1.73833895e-310]


In [13]:
matrix2 = np.array([(10,11,12),(13,14,15),(16,17,18)])

In [14]:
print(matrix1+matrix2)

[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [15]:
print(np.delete(matrix1, 1, axis=0))

[[1 2 3]
 [7 8 9]]


In [16]:
print(np.mean(matrix1, axis=0))

[4. 5. 6.]


In [17]:
print(matrix2[1,2])

15


In [18]:
print(matrix2[: , 1])

[11 14 17]


In [19]:
print(matrix2[matrix2 > 10])

[11 12 13 14 15 16 17 18]


In [20]:
print(matrix1 < 5)

[[ True  True  True]
 [ True False False]
 [False False False]]


In [21]:
matrix3 = np.array([(1,4,7),(3,8,5),(9,2,6),(11,0,22)])

In [22]:
print(matrix3[:,1])

[4 8 2 0]


In [23]:
print(matrix3[2,:])

[9 2 6]


In [24]:
matrix4 = np.array([(67,4,23),(44,12,7),(88,6,0),(65,2,17)])

In [25]:
print(np.append(matrix4,np.array([1,2,3])))

[67  4 23 44 12  7 88  6  0 65  2 17  1  2  3]


In [26]:
print(matrix4[matrix4 > 5])

[67 23 44 12  7 88  6 65 17]
